ReservedWord-> 'class'	at line: 2
ID-> 'Test'	at line: 2
Delimiter-> '{'	at line: 2
ReservedWord-> 'public'	at line: 4
ReservedWord-> 'static'	at line: 4
ReservedWord-> 'void'	at line: 4
ReservedWord-> 'main'	at line: 4
Delimiter-> '('	at line: 4
ReservedWord-> 'String'	at line: 4
Delimiter-> '['	at line: 4
Delimiter-> ']'	at line: 4
ID-> 'args'	at line: 4
Delimiter-> ')'	at line: 4
Delimiter-> '{'	at line: 4
ReservedWord-> 'System.out.println'	at line: 5
Delimiter-> '('	at line: 5
Integer-> '10000'	at line: 5
Delimiter-> ')'	at line: 5
Delimiter-> ';'	at line: 5
ReservedWord-> 'int'	at line: 7
ID-> 'len'	at line: 7
Delimiter-> '='	at line: 7
Integer-> '10'	at line: 7
Delimiter-> ';'	at line: 7
ReservedWord-> 'int'	at line: 8
ID-> 'b'	at line: 8
Delimiter-> '='	at line: 8
Integer-> '2'	at line: 8
ReservedWord-> 'int'	at line: 9
Delimiter-> '['	at line: 9
Delimiter-> ']'	at line: 9
ID-> 'a'	at line: 9
Delimiter-> '='	at line: 9
ReservedWord-> 'new'	at line: 9
ReservedWord-> 'int'	at line: 9
Delimiter-> '['	at line: 9
ID-> 'len'	at line: 9
Delimiter-> ']'	at line: 9
Delimiter-> ';'	at line: 9
ID-> 'a'	at line: 10
Delimiter-> '['	at line: 10
Integer-> '0'	at line: 10
Delimiter-> ']'	at line: 10
Delimiter-> '='	at line: 10
Integer-> '0'	at line: 10
Delimiter-> ';'	at line: 10
ID-> 'a'	at line: 11
Delimiter-> '['	at line: 11
Integer-> '1'	at line: 11
Delimiter-> ']'	at line: 11
Delimiter-> '='	at line: 11
Integer-> '1'	at line: 11
Delimiter-> ';'	at line: 11
ID-> 'a'	at line: 12
Delimiter-> '['	at line: 12
Integer-> '2'	at line: 12
Delimiter-> ']'	at line: 12
Delimiter-> '='	at line: 12
Integer-> '2'	at line: 12
Delimiter-> ';'	at line: 12
ID-> 'b'	at line: 13
Delimiter-> '='	at line: 13
ID-> 'a'	at line: 13
Delimiter-> '['	at line: 13
Integer-> '1'	at line: 13
Delimiter-> ']'	at line: 13
Operator-> '+'	at line: 13
Integer-> '1'	at line: 13
Operator-> '*'	at line: 13
Integer-> '2'	at line: 13
Operator-> '+'	at line: 13
ID-> 'a'	at line: 13
Delimiter-> '['	at line: 13
Integer-> '0'	at line: 13
Delimiter-> ']'	at line: 13
Delimiter-> ';'	at line: 13
ID-> 'a'	at line: 14
Delimiter-> '['	at line: 14
Integer-> '3'	at line: 14
Delimiter-> ']'	at line: 14
Delimiter-> '='	at line: 14
ID-> 'b'	at line: 14
Delimiter-> ';'	at line: 14
ID-> 'a'	at line: 15
Delimiter-> '['	at line: 15
Integer-> '4'	at line: 15
Delimiter-> ']'	at line: 15
Delimiter-> '='	at line: 15
Integer-> '4'	at line: 15
Delimiter-> ';'	at line: 15
ID-> 'a'	at line: 16
Delimiter-> '['	at line: 16
Integer-> '5'	at line: 16
Delimiter-> ']'	at line: 16
Delimiter-> '='	at line: 16
ID-> 'a'	at line: 16
Delimiter-> '['	at line: 16
Integer-> '4'	at line: 16
Delimiter-> ']'	at line: 16
Operator-> '+'	at line: 16
Integer-> '1'	at line: 16
Delimiter-> ';'	at line: 16
ID-> 'a'	at line: 17
Delimiter-> '['	at line: 17
Integer-> '6'	at line: 17
Delimiter-> ']'	at line: 17
Delimiter-> '='	at line: 17
ID-> 'a'	at line: 17
Delimiter-> '['	at line: 17
Integer-> '4'	at line: 17
Delimiter-> ']'	at line: 17
Operator-> '+'	at line: 17
Integer-> '2'	at line: 17
Delimiter-> ';'	at line: 17
ID-> 'a'	at line: 18
Delimiter-> '['	at line: 18
Integer-> '7'	at line: 18
Delimiter-> ']'	at line: 18
Delimiter-> '='	at line: 18
Integer-> '2'	at line: 18
Operator-> '+'	at line: 18
Integer-> '5'	at line: 18
Delimiter-> ';'	at line: 18
ID-> 'a'	at line: 19
Delimiter-> '['	at line: 19
Integer-> '8'	at line: 19
Delimiter-> ']'	at line: 19
Delimiter-> '='	at line: 19
ID-> 'a'	at line: 19
Delimiter-> '['	at line: 19
Integer-> '2'	at line: 19
Delimiter-> ']'	at line: 19
Operator-> '*'	at line: 19
Integer-> '4'	at line: 19
Delimiter-> ';'	at line: 19
ID-> 'a'	at line: 20
Delimiter-> '['	at line: 20
Integer-> '9'	at line: 20
Delimiter-> ']'	at line: 20
Delimiter-> '='	at line: 20
Integer-> '9'	at line: 20
Delimiter-> ';'	at line: 20
ReservedWord-> 'System.out.println'	at line: 22
Delimiter-> '('	at line: 22
Operator-> '/'	at line: 22
Integer-> '99999'	at line: 22
Delimiter-> ')'	at line: 22
Delimiter-> ';'	at line: 22
ReservedWord-> 'int'	at line: 24
ID-> 'i'	at line: 24
Delimiter-> '='	at line: 24
Integer-> '0'	at line: 24
Delimiter-> ';'	at line: 24
ReservedWord-> 'while'	at line: 25
Delimiter-> '('	at line: 25
ID-> 'i'	at line: 25
Operator-> '<'	at line: 25
ID-> 'a'	at line: 25
Delimiter-> '.'	at line: 25
ReservedWord-> 'length'	at line: 25
Delimiter-> ')'	at line: 25
Delimiter-> '{'	at line: 25
ID-> 'a'	at line: 26
Delimiter-> '['	at line: 26
ID-> 'i'	at line: 26
Delimiter-> ']'	at line: 26
Delimiter-> '='	at line: 26
ID-> 'i'	at line: 26
Delimiter-> ';'	at line: 26
ReservedWord-> 'System.out.println'	at line: 27
Delimiter-> '('	at line: 27
ID-> 'a'	at line: 27
Delimiter-> '['	at line: 27
ID-> 'i'	at line: 27
Delimiter-> ']'	at line: 27
Delimiter-> ')'	at line: 27
Delimiter-> ';'	at line: 27
ID-> 'i'	at line: 28
Delimiter-> '='	at line: 28
ID-> 'i'	at line: 28
Operator-> '+'	at line: 28
Integer-> '1'	at line: 28
Delimiter-> ';'	at line: 28
Delimiter-> '}'	at line: 29
ReservedWord-> 'System.out.println'	at line: 31
Delimiter-> '('	at line: 31
ID-> 'a'	at line: 31
Delimiter-> '.'	at line: 31
ReservedWord-> 'length'	at line: 31
Delimiter-> ')'	at line: 31
Delimiter-> ';'	at line: 31
Delimiter-> '}'	at line: 32
Delimiter-> '}'	at line: 33
ReservedWord-> 'class'	at line: 35
ID-> 'Test2'	at line: 35
Delimiter-> '{'	at line: 35
ReservedWord-> 'public'	at line: 36
ReservedWord-> 'int'	at line: 36
ID-> 'yeet'	at line: 36
Delimiter-> '('	at line: 36
ReservedWord-> 'int'	at line: 36
ID-> 'a'	at line: 36
Delimiter-> ','	at line: 36
ReservedWord-> 'boolean'	at line: 36
ID-> 'b'	at line: 36
Delimiter-> ')'	at line: 36
Delimiter-> '{'	at line: 36
ReservedWord-> 'return'	at line: 37
Integer-> '0'	at line: 37
Delimiter-> ';'	at line: 37
Delimiter-> '}'	at line: 38
Delimiter-> '}'	at line: 39
eof-> '$'	at line: 40
